version: "3.8"
services:
  order-service:
    build:
      context: ./order-service
    ports:
      - "8080:8080"
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8081
      - PAYMENT_SERVICE_URL=http://payment-service:8082
    depends_on:
      - inventory-service
      - payment-service

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8081:8081"

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8082:8082"
